services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    volumes:
      - /var/lib/docker/volumes/ollama:/root/.ollama
    networks: 
      - webui_net
    restart: on-failure
    ports:
      - "11434:11434"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

  tika:
    image: apache/tika
    container_name: tika
    networks:
      - webui_net
    restart: on-failure
    ports:
      - "9998:9998"

  open-webui:
    image: ghcr.io/open-webui/open-webui
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - WEBUI_AUTH=False
    volumes:
      - /var/lib/docker/volumes/open-webui:/app/backend/data
    networks: 
      - webui_net
    restart: on-failure
    ports:
      - "8080:8080"

  docling:
    image: quay.io/docling-project/docling-serve
    container_name: docling
    ports:
      - "5001:5001"
    environment: 
      - DOCLING_SERVE_ENABLE_UI=true 
    restart: on-failure
    networks:
      - webui_net

  postgres:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_NON_ROOT_USER
      - POSTGRES_NON_ROOT_PASSWORD
    volumes:
      - db_storage:/var/lib/postgresql/data
      - ./init-data.sh:/docker-entrypoint-initdb.d/init-data.sh
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -h localhost -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - webui_net

  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: always
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=${POSTGRES_DB}
      - DB_POSTGRESDB_USER=${POSTGRES_NON_ROOT_USER}
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_NON_ROOT_PASSWORD}
    ports:
      - 5678:5678
    links:
      - postgres
    volumes:
      - n8n_storage:/home/node/.n8n
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - webui_net
networks:
  webui_net:
    driver: bridge

volumes:
  db_storage:
  n8n_storage:

